[package]
name = "sdkman-cli-native"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
assert_cmd = "2.0"
predicates = "2"
edit = "0.1.3"
