[package]
name = "sdkman-cli-native"
version = "0.2.2"
edition = "2018"
publish = false

[dependencies]
clap = "3.1.18"
assert_cmd = "2.0.4"
predicates = "2.1.1"
colored = "2.0.0"
textwrap = "0.15.0"
